### ISSUE TITLE
Feature request: Notification after the process completion

### ISSUE THREAD

**Issue by kamthamc** [karma-runner/karma-coverage#181]
Feature Request:
Can anyone please add a notifier or event emitter (event name can be configured in the karma configuration) after process/ reporting is completed? 

My specific use case is I have to update the thresholds to the maximum using gulp once the karma coverage is completed. I can't rely on karma exit event as the event is generated before the file is created. I couldn't find a way to track the status of any plugin.

**Comment by quetzalcoatl** [comment]
I've found your request by accident, I was looking for such even tmyself. I did not found any. There's CoverageReporter (`lib\reporter.js`) which writes reports asynchronously, waits for all writes to complete, delays `onExit` processing until (caches `done` callback and calls it back only after all writing finishes), and nothing more happens there.

Having the same problem as you, I've found two solutions **for now**.

(1) is very simple: on start (or better before Karma starts) delete or move aside all reports, then place a filewatcher (chokidar, etc) observing when the reports show up. You can improve that even more by adding your own dummy-reporter that:
- observes `onRunStart` and deletes a "syncfile"
- observes `onRunComplete` and creates a "syncfile"
If you now ensure that your dummy-reporter is the last on the reporter in the config, then I think karma-coverage will invoke it last. You can then just observe the "syncfile" instead of the report files and watch for "file created" event.

(2) I'm working on another plugin (but not for karma-coverage), and I found a "hack" to override `CoverageReporter.onRunComplete` with my own method. This way you can inject emitting event or doing anything you want.

    var karmaCoverageReporter = require('karma-coverage')['reporter:coverage']
    var oldCtor = karmaCoverageReporter[1];

    var newCtor = function() {
        console.log('YAY, karma-coverage reporter-ctor was intercepted!');
        var ret = oldCtor.apply(this, arguments);
        var oldrc = this.onRunComplete;
        this.onRunComplete = function () {
            console.log('YAY, karma-coverage onRunComplete was intercepted!');
            var res = oldrc.apply(this, arguments); // call original OnRunComplete that writes files

            //** call any callbacks here **//

            return res;
        };
        return ret;
    };

    newCtor.$inject = oldCtor.$inject;
    karmaCoverageReporter[1] = newCtor;

In that place I'm successfuly reading the most-current results from JsonReporter, so you may find it useful. Still, that's all hackish and some way of designed/documented notification/callback would be very useful.
